### ISSUE TITLE
Add Josh and Chase to Twilio dashboard

### ISSUE THREAD

**Issue by jetilling** [zachsimunic/HungerCurbed#1]
We'll need access to the Twilio dashboard in order to view sent/recieved/failed messages, among other things.

**Comment by jetilling** [comment]
I'm not sure how adding users works, but our emails are:
josh@futurewonder.com
crussell@futurewonder.com

**Comment by zachsimunic** [comment]
Josh, both of you have been added. Please let me know if there are any issues. One thing to note is that we have two numbers in the account. The one that has a title that includes "testing" is our test account so feel free to use that one if that helps. The other number has been published and still occasionally gets a text.

**Comment by Chase-R** [comment]
I've not received an invite to the Twilio account yet.

**Comment by zachsimunic** [comment]
@Chase-R - resent the invite. Also updated you on the issue in Slack

**Comment by Chase-R** [comment]
Worked!
