### ISSUE TITLE
Dashboard framework

### ISSUE THREAD

**Issue by jetilling** [zachsimunic/HungerCurbed#11]
Figure out how we want to build our dashboard. 

Do we want to pull in a laravel package (should think about longevity, cost, does it do what we want, how does it fit into our project)

Or should we build our own (it'll be simple, we have control, it'll do exactly what we want, we'll know how it works)

**Comment by Chase-R** [comment]
Basic styling on the app header:
![image](https://user-images.githubusercontent.com/26582647/64875532-4fa22c00-d61b-11e9-8d36-f93ffb1e2bd1.png)

Then logged in:
![image](https://user-images.githubusercontent.com/26582647/64875562-5f217500-d61b-11e9-9015-0512e6f85970.png)

**Comment by Chase-R** [comment]
All the pages have stubs in place for now, so no 404's as you click around.
