### ISSUE TITLE
Truck page (add, update, open / closed, disable, delete)

### ISSUE THREAD

**Issue by jetilling** [zachsimunic/HungerCurbed#12]
From the project document:
```
As mentioned above, we will provide an on-demand list of all active food trucks in the
Bloomington area. In order to do this, we will need to pull from a master list of trucks and display
only the ones that we have marked as live. For this table, we will need the name of the truck,
open time, close time, a variable for open or close (based on current time falling within the open
or close time), and a column for the trucks’ current addresses (which will be manually filled in for
the time being).
```

**Comment by Chase-R** [comment]
Truck table columns:
- name = The name of the truck
- open_time = The time the truck generally opens each day
- close_time = The time the truck generally closes each day
- current_address = The address the Truck is physically located at the current time.

I'm not going to add a column for "a variable for open or close (based on current time...)", as this is a calculated field that should not be committed to the database.

**Comment by Chase-R** [comment]
Bam!
![image](https://user-images.githubusercontent.com/26582647/65062894-0c152e00-d94b-11e9-9fd2-4a9a6117ebf4.png)

With Editing:
![image](https://user-images.githubusercontent.com/26582647/65062947-2bac5680-d94b-11e9-910f-64c66b3b918e.png)

And Errors:
![image](https://user-images.githubusercontent.com/26582647/65062978-3d8df980-d94b-11e9-8f4c-c7ff975aad26.png)
