### ISSUE TITLE
Create an AWS EC2 account

### ISSUE THREAD

**Issue by jetilling** [zachsimunic/HungerCurbed#4]
In order to 1) use the app and 2) test with Twilio we'll need to deploy the app to AWS. 

We prefer AWS as it is widely used in the industry, reliable, and provides us with a lot of features. DigitalOcean is another option, but doesn't provide as many features or scaling options.

**Comment by zachsimunic** [comment]
What is your AWS usernames?

**Comment by Chase-R** [comment]
We'll use the same email accounts, if that's the username it wants:
josh@futurewonder.com
crussell@futurewonder.com

We need IAM accounts associated to your main AWS account.

**Comment by zachsimunic** [comment]
Great sent your way

**Comment by hubpuller** [comment]
Zach, can you take another look at this - neither Chase nor Josh received an IAM invitation.

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html

They will need console access, ideally admin to start to cut down on more IAM permission requests.

**Comment by zachsimunic** [comment]
@hubpuller - I went back in this morning and reworked their permissions. I have attached screen shots of what I see on my side. @Chase-R and @jetilling please let me know if you now have access. 
<img width="714" alt="Screen Shot 2019-08-26 at 8 32 26 AM" src="https://user-images.githubusercontent.com/44904908/63691051-39ebd480-c7dc-11e9-8004-943391257561.png">
<img width="731" alt="Screen Shot 2019-08-26 at 8 32 18 AM" src="https://user-images.githubusercontent.com/44904908/63691052-39ebd480-c7dc-11e9-98d8-322c29b31e5d.png">
