### ISSUE TITLE
Connect our app to Twilio

### ISSUE THREAD

**Issue by jetilling** [zachsimunic/HungerCurbed#5]
In order to use Twilio we'll need to connect it to Laravel.

Twilio has documentation here: https://www.twilio.com/docs/sms/quickstart/php
And a Laravel/Twilio documentation: https://www.twilio.com/docs/sms/tutorials/server-notifications-php-laravel

After this issue our app should be able to send texts through twilio.

**Comment by Chase-R** [comment]
I need Twilio account stuff before I can do this:
// Your Account SID and Auth Token from twilio.com/console
$account_sid = 'ACXXXXXXXXXXXXXXXXXXXXXXXXXXXX';
$auth_token = 'your_auth_token';

// A Twilio number you own with SMS capabilities
$twilio_number = "+15017122661";

**Comment by Chase-R** [comment]
Refs #1 for the Twilio login creds.

**Comment by Chase-R** [comment]
We will need to add ENV variables to any new installations of this app for this to work, so I'll also be updating the wiki.
